name: Labeler

on:
  - pull_request_target

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/labeler@v7
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
